#qq邮箱smtp服务器
host_server: smtp.qq.com
#sender_qq为发件人的qq号码
sender_qq: 1234567890
#pwd为qq邮箱的授权码
pwd: pserndadcevljbaaa
#发件人的邮箱
sender_qq_mail: example<example@qq.com>
#收件人邮箱
receiver: example@gmail.com
