# genome data
genome: /public/home/mowp/db/Arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa
gtf: /data/Zhaijx/mowp/db/Arabidopsis_thaliana/gtf/Araport11_GTF_genes_transposons.Mar202021.gtf

sample_name: 20210324_col_nuclear 
