import os
from glob import glob
import pandas as pd

configfile: 
    "config.yml"

workdir:
    config['workdir']

mode = config['mode']
suffix = config['suffix']
sep = config['sep']

if mode == 'pe':
    chipseq_smk = 'chipseq_pe.smk'
else:
    chipseq_smk = 'chipseq_se.smk'

# Check if the sample table has control columns
sample_table = config['sample_table']
try:
    sample_tabel_df = pd.read_csv(sample_table, sep='\t', header=None)
    if sample_tabel_df.isna().any().sum() == 0:
        callpeak_smk = 'callpeak_with_control.smk'
    else:
        callpeak_smk = 'callpeak_without_control.smk'
except:
    callpeak_smk = 'callpeak_without_control.smk'

include:
    "snakemake/"+chipseq_smk

include:
    "snakemake/"+callpeak_smk

sample_name = [os.path.basename(fn.split(sep)[0]) for fn in sorted(glob(f'raw_data/*{sep}{suffix}'))]
print('Sample names: ', end='')
for _sample_name in sample_name:
    print(_sample_name, end=',')
print()

rule all:
    input:
        expand('aligned_data/{sample_name}.sorted.rmdup.bam', sample_name=sample_name),
        expand('bw_files/{sample_name}.sorted.rmdup.CPM.bw', sample_name=sample_name),
        expand('deeptools_profile/{sample_name}.scale.png', sample_name=sample_name),

rule callpeak:
    input:
        'macs2_result/{treatment}_peaks.narrowPeak',
        'bw_compare/{treatment}.compare.bw',
        'replicate_intersect/{replicate}_intersect.bed'
