# snakemake
mode: pe
workdir: .

# genome
genome: /data/user/mowp/db/hg38/chr/hisat2_index/genome
ann_gff: /data/user/alldata/db/refdata-gex-GRCh38-2020-A/genes/genes.gtf

suffix: .fq.gz
sep1: _1
sep2: _2