# genome
bwa_index: /data/user/mowp/db/hg38/chr/bwa_index/hg38.fa
genomesize: /data/user/mowp/db/hg38/chr/hg38.size

# pairtools mapq
mapq: 10
# cooler
resolution: 5000
# mcool
mcool_resulation: '5000,10000,25000,50000,100000,250000,500000,1000000'

effectiveGenomeSize: 2913022398