# snakemake
mode: pe
workdir: .

# genome
genome: /data/user/mowp/db/mm10/dna/bowtie2_index/genome.fa
bed: /data/user/mowp/db/mm10/bed/genes.bed
gsize: mm

# sample
suffix: .fq.gz
sep: _1

# software
picard_path: /data/software/picard.jar

# Comma-separated list of chromosomes to exclude for Genrich
exclude_chroms: chrM