import os
from glob import glob

configfile: 
    "config.yml"

workdir:
    config['workdir']

mode = config['mode']
suffix = config['suffix']
sep = config['sep']

if mode == 'pe':
    snakefile = 'atac_pe.smk'
else:
    snakefile = 'atac_se.smk'

include:
    "snakemake/"+snakefile

sample_name = [os.path.basename(fn.split(sep)[0]) for fn in glob(f'raw_data/*{sep}{suffix}')]

# onsuccess:
#     shell("email_log.py log -l {log}")

# onerror:
#     shell("email_log.py log -l {log} --return_code 1")

rule all:
    input:
        expand('aligned_data/{sample_name}.sorted.rmdup.bam', sample_name=sample_name),
        expand('bw_files/{sample_name}.sorted.rmdup.CPM.bw', sample_name=sample_name),
        expand('deeptools_profile/{sample_name}.scale.png', sample_name=sample_name),
        expand('macs2_result/{sample_name}_peaks.narrowPeak', sample_name=sample_name),
        expand('genrich_result/{sample_name}_peaks.narrowPeak', sample_name=sample_name)
